[package]
name = "rips"
version = "0.1.0"
authors = ["Haikel Guemar <hguemar@fedoraproject.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
